### PR TITLE
Fixed enhancement issue for puzzle cell classes extending from GridCe…

### PR DESCRIPTION
**Pull request by Mbijur**
…ll as Integer types to respective types for Masyu, Nurikabe, Skyscrapers, and TreeTent puzzles.

## Description

Changed puzzle cell classes extending from GridCell <Integer> to the specific puzzle type. Issue #139 

Closes #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Corppet** [comment]
Please mark down the **Type of Change** and any actions you have fulfilled in the **Checklist** in your original Pull Request.

**Comment by Corppet** [comment]
Please make sure your changes do not cause compiler errors. Simply changing the extended type in the `GridCell` generic does not resolve the issue and requires other errors to be resolved.

**Comment by charlestian23** [comment]
I removed the flag name change, since that would best be done in a separate pull request on a separate branch. Additionally, those changes also require you to change how the Short Truth Table importer reads the files.

**Comment by Corppet** [comment]
Closing this pull request because no changes have been made for the past two weeks and current changes have failed both checks. Please make a new pull request if you want to add further changes.

**Pull request closed without merging**
