### PR TITLE
Two-finger scroll bug

### PR DESCRIPTION
**Pull request by JQCBozz**
Two-finger scrolling fix.

### CODE REVIEW

**Comment by charlestian23** [comment]
Which issue would this close? Could you give me an issue number?

**Comment by JQCBozz** [comment]
Issue 114

**Review by Chase-Grajeda — APPROVED** [review]
Implementation is good, passes tests

**Comment by Chase-Grajeda** [comment]
Will be reopening #114 ; the zoom bar still does not update upon zoom

**Pull request merged**
