### PR TITLE
[WIP] #106 changed redo from ctrl+y to ctrl+shift+z

### PR DESCRIPTION
**Pull request by deShortOne**
Don't have access to mac so WIP and will need to be tested

### CODE REVIEW

**Comment by deShortOne** [comment]
Hi, yes it does change it.
image

**Comment by Chase-Grajeda** [comment]
Closing pull request. I've tested the changes and they work, however this merge is going straight into master. Please create a new branch under dev, make the same edits, then request another merge from new branch -> dev 

On creating new branches and making merge requests, please see the corresponding sections in attached wiki 
https://github.com/Bram-Hub/Legup/wiki/Programming-Principles

**Comment by deShortOne** [comment]
Sorry about merging it incorrectly, if possible, could you put it in a contributing.md for future people?

**Comment by charlestian23** [comment]
> Sorry about merging it incorrectly, if possible, could you put it in a contributing.md for future people?

Will do, I'll make one tomorrow.

**Review by charlestian23 — APPROVED** [review]

**Pull request merged**
