### PR TITLE
Overhaul of Various TreeTent Tests (Current Tests in Pull Request: 4)

### PR DESCRIPTION
**Pull request by Rorymar**
## Description

Overhauled the tests for the NoTreeForTent and TouchingTents part of the Test Suite (As such, it is related to those issues) For TouchingTents, added testing of various directional orientations to see if that affected the results and simultaneous occurrences of adjacent and diagonal contradiction. For NoTreeForTent, added testing of various orientations similar to how was implemented for TouchingTents, but also tested with some 3x3 situations.

Closes [Test] Touching Tents Test
Closes [Test] No Tree for Tent Test

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Ran the tests and ensured they all passed. To verify I was only looking at the exact tests I was working on, I used this process:

1. Went to LEGUP > test > java > puzzles > treetent.rules
2. Right-clicked a Test, for example, TouchingTentContradictionRuleTest.java
3. Pressed 'Run' in the right-click options
4. Observe the result 

I then made sure the number of passed tests matched the tests tested. I also ran the entire test suite from LEGUP > test, and that also produced no non-functional tests.

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rorymar** [comment]
I added some additional Tests to my branch, so here is the information for them:
## Description

Overhauled the tests for the NoTentForTree and Surround With Grass part of the Test Suite. For NoTentForTree, added some tests for specifically diagonal and adjacent failures, and a test where one tent was ok, but one was not. For Surround, added extreme case tests that looked at puzzles with absolutely nothing but a tent in the middle of a 3x3, and another with a 3x3 with a tent completely surrounded by trees.


Closes [Test] No Tent for Tree Test
Closes [Test] Surround Test With Grass Test 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested? (Same as original process)

Ran the tests and ensured they all passed. To verify I was only looking at the exact tests I was working on, I used this process:

1. Went to LEGUP > test > java > puzzles > treetent.rules
2. Right-clicked a Test, for example, TouchingTentContradictionRuleTest.java
3. Pressed 'Run' in the right-click options
4. Observe the result 

I then made sure the number of passed tests matched the tests tested. I also ran the entire test suite from LEGUP > test, and that also produced no non-functional tests.

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Comment by jac-oblong** [comment]
Please change the destination of the PR to Bram-Hub:dev instead of Bram-Hub:master

**Comment by jac-oblong** [comment]
I'm not entirely sure what happened, but when the PR was opened only ~28 files were changed. There are currently 89 files that are changed, many of them not related to the PR topic.

**Comment by Rorymar** [comment]
> I'm not entirely sure what happened, but when the PR was opened only ~28 files were changed. There are currently 89 files that are changed, many of them not related to the PR topic.

I believe it is the October Merge that is causing that numerical change, which occurred while I was working on my changes.

**Comment by charlestian23** [comment]
Fixed the ~89 files issue, you can review it now @jac-oblong

**Comment by charlestian23** [comment]
@Rorymar Ivan just merged #648, which is where I deleted a bunch of files that shouldn't be in the repo. All the merge conflicts you see should just be files that were in build. To resolve them, you can just safely delete all of them.

**Review by jac-oblong — APPROVED** [review]
Everything looks good

**Pull request merged**
