### PR TITLE
Added more Short Truth Table tests

### PR DESCRIPTION
**Pull request by charlestian23**
## Description

Added tests for Biconditional Elimination, Conditional Elimination, and Not Elimination. One of the tests for Not Elimination is commented out because it fails, but that seems to be correct, as there does seem to be a bug with the rule (see #684).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Bram28 — COMMENTED** [review]
For the conditional case A -> B where the -> is false:  does it check that it is ok to just set A to true or just set B to false?

For the biconditional A <-> B: you have tests where A and <-> have given truth-values ... do you need to add tests where <-> and B have given truth-values? It should be completely symmetrical, but still ...

**Comment by charlestian23** [comment]
For the first question, no. I forgot about those test cases and will add them shortly. For the second question, I figured they would be symmetric, but I will add test cases for them too just in case.

**Comment by charlestian23** [comment]
@Bram28 I just added in more tests for the conditional case and biconditional cases you mentioned.

**Review by Corppet — CHANGES_REQUESTED** [review]
```
puzzles.shorttruthtable.rules.NotEliminationTest > CannotSetBothAtOnceTest FAILED
    java.lang.NullPointerException at NotEliminationTest.java:120
```
Even if this is the intended behavior, the unit test should be marked as passed, otherwise this could interfere with future checks on other pull requests.

**Comment by charlestian23** [comment]
> ```
> puzzles.shorttruthtable.rules.NotEliminationTest > CannotSetBothAtOnceTest FAILED
>     java.lang.NullPointerException at NotEliminationTest.java:120
> ```
> 
> Even if this is the intended behavior, the unit test should be marked as passed, otherwise this could interfere with future checks on other pull requests.

Commented out the test case, I'll make a note in #684 that the test case should be uncommented once the issue is fixed.

**Pull request merged**
