### PR TITLE
UI problem for the treeview zoomfit()

### PR DESCRIPTION
**Pull request by wei-jun7**
fix the treeview zoomfix bug

### CODE REVIEW

**Review by charlestian23 — CHANGES_REQUESTED** [review]
The board resize button resizes both the board and the proof tree panels, but it should only resize the board panel. The proof tree panel's resize button also does not center the resized tree.

**Comment by wei-jun7** [comment]
it is fix this bug which it will resize both when you push the button

**Comment by charlestian23** [comment]
This may not be needed anymore after the changes in #235, but will double check and come back and close this if that is true

**Comment by charlestian23** [comment]
Fixed in #246

**Pull request closed without merging**
