### PR TITLE
Tree Tent Test Suite- All Remaining Non-Case Type Tests

### LINKED ISSUE #603: [TEST] Finish With Grass Test
Implement and overhaul the tests for the direct rule. Clearly comment and show what you are testing. Try to cover all inputs and cases that may throw an uncaught exceptions.

### LINKED ISSUE #604: [TEST] Finish With Tents
Implement and overhaul the tests for the direct rule. Clearly comment and show what you are testing. Try to cover all inputs and cases that may throw an uncaught exceptions.

### LINKED ISSUE #605: [TEST] Last Camping Spot Test
Implement and overhaul the tests for the direct rule. Clearly comment and show what you are testing. Try to cover all inputs and cases that may throw an uncaught exceptions.

### LINKED ISSUE #615: [TEST] Too Few Tents Test
Implement and overhaul the tests for the contradiction rule. Clearly comment and show what you are testing. Try to cover all inputs and cases that may throw an uncaught exceptions.

### LINKED ISSUE #616: [TEST] Too Many Tents Test
Implement and overhaul the tests for the contradiction rule. Clearly comment and show what you are testing. Try to cover all inputs and cases that may throw an uncaught exceptions.

### PR DESCRIPTION
**Pull request by Rorymar**
## Description

Expanded all remaining tests for TreeTent's rules not under the "case" category to be more comprehensive and better cover potential edge cases.

Closes #616 
Closes #615 
Closes #604 
Closes #603 
Closes #605 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

For each Test being expanded, it was tested overall in the Tree Tent tests and then also running the specific individually. 

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Bram28 — COMMENTED** [review]
TooFewTents: Using a 1x1 board might be an edge case itself ... I would add a test case with a 2x2 or 3x3 board where the contradiction occurs in only one or some of the columns or rows ... analogous to what you do with testing TooManyTents

For any of the contradiction rules: please make sure you test for incorrect or 'false' applications of those rules, i.e. that LEGUP correctly responds by saying that some contradiction rule does not check out ... because there is indeed no contradiction of the kind that the contradiction rule is supposed to point out.

Same with Direct rules:  make sure to have test cases where the Direct rule application should *not* check out

 Starting with FinishWithGrass: please comment test cases

**Comment by Corppet** [comment]
Changing this pull request to a draft, since there hasn't been any updates for a while and there seems to be changes that still need to be made.

**Comment by charlestian23** [comment]
Marking this PR as ready for review. I will review it and then make Bram's comment a new issue.

**Review by charlestian23 — APPROVED** [review]
Tests that were added seem good.

**Pull request merged**
