### PR TITLE
Fix treetent puzzle editor

### LINKED ISSUE #503: [BUG] Tree Tent puzzle editor does not work
### Description

Despite being one of the puzzles that is marked as completed, Tree Tent does not fully function in the puzzle editor. Some functions are just not implemented.

### Steps to Reproduce

1. Open LEGUP
2. Click on "Create Puzzle"
3. Select Tree Tent and give any valid dimensions
4. Attempt to create a puzzle and notice that it does not work

### Expected Behavior

The Tree Tent puzzle editor should work as intended, just like Nurikabe.

### Screenshots

_No response_

### Puzzle Files

_No response_

### Additional Context

This issue is intended to be worked on by multiple people, who can reference Nurikabe for how to finish implementing the Tree Tent puzzle editor.

### PR DESCRIPTION
**Pull request by jac-oblong**
## Description
Uses the code from #530 to fix the treetent puzzle editor.

Where very simple fixes. There was a switch statement missing "break"s. And the TreeTent puzzle exporter was exporting string values, while the importer expected integers.

Closes #503, #530

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Created a puzzle using the editor and successfully opened it back up.

## Checklist:

- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if applicable)
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jac-oblong** [comment]
Once this is merged, #530 should be closed.

**Review by charlestian23 — COMMENTED** [review]
Looks fine from a quick check, if you saw no issues @jac-oblong then you can merge this pull request.

**Comment by charlestian23** [comment]
I'm dumb, just realized the author is you, I'll check it more thorougly right now lol

**Review by charlestian23 — CHANGES_REQUESTED** [review]
The changes you made are fine. I'd prefer if right clicking the numbers in the Tree Tent puzzle editor would decrease the numbers, since right now, right clicking and left clicking both increases them.

**Comment by jac-oblong** [comment]
Differing between right/left click should work now

**Pull request merged**
