### PR TITLE
changed 'Atomic Rule' to 'True or False' and changed case/Atomic.png …

### PR DESCRIPTION
**Pull request by sparakala21**
…to a new image that is more indicative of the rule.

## Description

Closes #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
i ran the file and saw that the new image is in the rules tab. i also clicked the button and it worked properly

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by charlestian23 — CHANGES_REQUESTED** [review]
I think you should make the black part of the icon green instead, so it's clear for the user that the atomic case rule create one branch with red and one branch as green

**Comment by sparakala21** [comment]
> I think you should make the black part of the icon green instead, so it's clear for the user that the atomic case rule create one branch with red and one branch as green

just fixed that

**Comment by charlestian23** [comment]
I talked to Bram, he likes the new icon. If you can fix the conflicts, that would be great. Just re-request a review when you're done with that and I'll merge the pull request.

**Comment by charlestian23** [comment]
@VortiganOfficial Officially merged, you can go ahead and update the documentation.

**Pull request merged**
