### PR TITLE
Batch Grader Fix, "isSolved" Flag and Related Stuff

### LINKED ISSUE #227: [ENHANCEMENT] Improve batch grader speed with multithreading
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Currently, the batch grader is slow when grading for many, many students. Improving the speed of the batch grader would allow educators to get the student grades quicker.

### Describe the improvement you'd like

Consider using multithreading to help speed up the batch grader process. We could create a separate thread for each student rather than going through all the students iteratively.

### Describe alternatives you've considered

A possible addition of a "grade-by-flag" implementation was considered, where if a proof was deemed correct by the Legup software, a flag would be added to verify that the proof was correct. This would allow the batch grader to check for that flag first before needing to manually verify the proof itself.

### Additional Context

_No response_

### LINKED ISSUE #547: [Batch Grader] Things missing or mistaken in Batch Grader output file
### Description

The Batch grader output file has a couple of issues:

1. It does not show whether problem was correctly solved or not
2. It does not go into any folders
3. If someone has empty folder, it does not create new line

We had these issues before .. and Chase had fixed them...but now the issues are back. Here is a screenshot from the spreadsheet I got from the lastest LEGUP version (version 5.0.1):

image

Problem 1:  line 2 it shows boesec followed by cristn.  These are both student folders. boesec's fodler was empty, so it should have left the rest of that line blank and a new line should have been created for cristn
Problem 2:  No indication at all whether problem was solved or not in column C
Problem 3: If you look at line 10 you see that student fanx4 had created separate hw6 and hw7 subfolders, and the Batch garder should have gone into those folders to find and grade the solution files ... but it didn;t.

### Steps to Reproduce

1. Create folder with a bunch of subfolders (idea is that each student has a subfolder where they put their solution files).  There may be subsubfodlers as well (e.g. a student may create a folder for each different HW within their own folder)
2. Run LEGUP and choose Batch Grader
3. Select the main folder
4. When Batch grader is done, there will be a excel spreadsheet in main folder
5. Open that spreadsheet and you'll see what I am talking about. Here is a screenshot of something I got:

### Expected Behavior

Here is the output from the Batch grader from LEGUP version 3:

image

So here it does everything correctly!  Unfortunately, this batch grader is also very slow. Chase had later improved the Batch grading to be much quicker (I think what Chase did was that solution files would effectively store a simple flag whether or not proof was correct, so that Batch grader just looks aat that flag rather than that it would try to recheck the whole proof) ... but now the earlier issues are back

### Screenshots

See above

### Puzzle Files

_No response_

### Additional Context

_No response_

### LINKED ISSUE #564: Implement an "isSolved" attribute in puzzle templates and saved proofs
### Description

Implement a "isSolved" flag to indicate whether a proof has been completed or not. This is one of the features what were supposed to be, but not implemented in the past versions of LEGUP.

From my conversation with Chase, "isSolved" flag is described as:

> The isSolved flag always remains False until a puzzle is proved correct and saved. If an edit is made to the proved puzzle and the solution is not verified again, the flag should revert back to False until the previous condition is met again. 

Which is the root of why the batch grader hasn't been working correctly since version 3.0.2.  Batch grader currently uses a method `use_xml_to_check()` to check for this flag in the .xml file representation of the proofs, but since the flag is missing, the batch grader writes nonsense to `result.csv`.

### Steps to Reproduce

1. go to home panel
2. click on batch grader
3. select a folder to grade
4. see result.csv and console errors

### Expected Behavior

The batch grader works correctly, with improved speed for processing files, using the `use_xml_to_check()` method instead of `checkFolder()`

### Screenshots

_No response_

### Puzzle Files

_No response_

### Additional Context

related issues: #547

### PR DESCRIPTION
**Pull request by hansongu123**
## Description

- xml parser
- "isSolved" flag

Here's the implementation of the Batch Grader using an .xml parser to traverse through a collection of student submission files, reading the attribute value of "isSolved" flag (which was planned to be implemented in the earlier versions) to improve its processing efficiency.

Two attributes have been added to the exporter. One is the "isSolved" flag - runs puzzle checker when a proof is saved (instead of running it inside of the Batch Grader); Another is "lastSaved" - give the exact time the proof is last saved. (meant to be a supporting function for the isSolved flag, from our group discussion, as a way to hash its value)

The default values of these attributes are also added to the template puzzle files.

Some small changes are also included, like the names of the save buttons in the menu panel.

Closes #547
Closes #564
Closes #227 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to an already existing feature)

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hansongu123** [comment]
For the ease of reviewing, the main changes are located in HomePanel.java and PuzzleExporter.java

**Comment by 04vmatsibekker** [comment]
When testing this PR out after saving one of the puzzle files some issues came up. At first I noticed no changes to the puzzle file, isSaved column. Then after multiple attempts of saving one of Cristn's puzzles with a slight change, I did get a result, but it is not quite correct yet. 
image_480


I have been discussing this PR with Hanson for the past few days. And it seems that it works for him, but somehow not for me, despite verifying that I tested the PR out correctly.

**Review by Chase-Grajeda — APPROVED** [review]
Fixed remaining bug for unexpected spreadsheet output when flag element is missing. Passes tests

**Comment by hansongu123** [comment]
Thanks! I'm happy that this is finally approved

**Pull request merged**
